//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduPMSDAL.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class TenantDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TenantDetail()
        {
            this.Users = new HashSet<User>();
        }
    
        public System.Guid Tenant_Id { get; set; }
        public string Tenant_Name { get; set; }
        public string Tenant_Description { get; set; }
        public string Tenant_Address { get; set; }
        public string Tenant_Website { get; set; }
        public string Tenant_Contact { get; set; }
        public string Tenant_BillingType { get; set; }
        public string Tenant_PaymentDetails { get; set; }
        public string Tenant_BillingContact { get; set; }
        public string Tenant_BillingAddress { get; set; }
        public Nullable<bool> Tenant_IsProductAdmin { get; set; }
        public string Tenant_URL { get; set; }
        public string Tenant_CreatedBy { get; set; }
        public System.DateTime Tenant_CreatedOn { get; set; }
        public Nullable<System.DateTime> Tenant_UpdatedOn { get; set; }
        public string Tenant_UpdatedBy { get; set; }
        public bool Tenant_Status { get; set; }
        public string Tenant_ApprovalStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
